name: Cache PNG and JPG Files

on:
  push:
    branches:
      - main

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Cache PNG and JPG Files
        uses: actions/cache@v2
        with:
          path: |
            path/to/png/files/*.png
            path/to/jpg/files/*.jpg
          key: ${{ runner.os }}-png-jpg-${{ hashFiles('path/to/png/files/*.png') }}-${{ hashFiles('path/to/jpg/files/*.jpg') }}

      # Add additional steps for your workflow here
